-- Skip providers
vim.g.loaded_python3_provider = 0
vim.g.loaded_node_provider = 0
vim.g.loaded_ruby_provider = 0
vim.g.loaded_perl_provider = 0

-- Disable distribution plugins
vim.g.loaded_matchit = 1
vim.g.loaded_matchparen = 1
vim.g.zipPlugin = 0
vim.g.loaded_gzip = 0
vim.g.loaded_zip = 0
vim.g.loaded_zipPlugin = 0
vim.g.loaded_tar = 0
vim.g.loaded_tarPlugin = 0
vim.g.loaded_getscript = 0
vim.g.loaded_getscriptPlugin = 0
vim.g.loaded_vimball = 0
vim.g.loaded_vimballPlugin = 0
vim.g.loaded_2html_plugin = 0
vim.g.highlighturl_enabled = 1
vim.g.load_black = 0
vim.g.loaded_logiPat = 0
vim.g.loaded_rrhelper = 0
vim.g.loaded_netrwFileHandlers = 0
vim.g.loaded_netrw = 0
vim.g.loaded_netrwPlugin = 0
vim.g.loaded_netrwSettings = 0
vim.g.loaded_remote_plugins = 0
